"""Audited persistent parameter ownership, independent of labels and UI indexes.

Changes to the parameter schema must update this map; unlisted fields block projection.
"""

PARAMETER_OWNERS = {'caseName': 'shared',
 'inputVolume': 'shared',
 'inspectedVolume': 'shared',
 'inspectedSegmentation': 'shared',
 'roundTripVolume': 'shared',
 'teethSegmentation': 'shared',
 'useLauncherBackendConfiguration': 'shared',
 'wslDistribution': 'shared',
 'wslPythonPath': 'shared',
 'stagingRoot': 'shared',
 'inferenceDevice': 'shared',
 'workflowStageIndex': 'navigation',
 'dentoCaseSchemaVersion': 'registry',
 'step6TrajectoryRegistryJson': 'registry',
 'step6SchemaMigrationPending': 'registry',
 'sceneDisplayPresetJson': 'display',
 'step6CbctVolumeRenderingNodeId': 'display',
 'step6CbctOpacity': 'display',
 'step6MasksOpacity': 'display',
 'step6RobotOpacity': 'display',
 'step6GoalRobotOpacity': 'display',
 'step6GuidesOpacity': 'display',
 'step6MountPlaneOpacity': 'display',
 'step6TrajectoryOpacity': 'display',
 'step6ForeheadProxyOpacity': 'display',
 'step6CollisionAuditOpacity': 'display',
 'step6CaseJawLandmarks': 'foundation.pose',
 'step6CaseJawTransform': 'foundation.pose',
 'step6CaseJawGapLine': 'foundation.pose',
 'step6OpenedLowerJawModel': 'foundation.pose',
 'step6FixedUpperAnatomy': 'foundation.pose',
 'step6MovingLowerAnatomy': 'foundation.pose',
 'step6TargetJawFallbackAnatomy': 'foundation.pose',
 'caseFoundationFixedUpperVolume': 'foundation.pose',
 'caseFoundationMovingLowerVolume': 'foundation.pose',
 'caseFoundationOpeningRevision': 'foundation.pose',
 'caseFoundationPreviewUncommitted': 'foundation.pose',
 'step6CaseJawTargetGapMm': 'foundation.pose',
 'step6CaseJawPreparationMode': 'foundation.pose',
 'step6CaseJawPreparationJson': 'foundation.pose',
 'step6CaseJawLastFailureJson': 'history',
 'step6EnvironmentJson': 'foundation.pose',
 'robotBaseTransform': 'foundation.base',
 'robotMountPlane': 'foundation.base',
 'robotForeheadProxyModel': 'foundation.base',
 'robotBaseMountLocked': 'foundation.base',
 'step6BasePlacementStatus': 'foundation.base',
 'step6BasePlacementSource': 'foundation.base',
 'step6BasePlacementRevision': 'foundation.base',
 'step6ForeheadProxyWidthMm': 'foundation.base',
 'step6ForeheadProxyHeightMm': 'foundation.base',
 'step6ForeheadProxyDepthMm': 'foundation.base',
 'step6ForeheadProxyOffsetMm': 'foundation.base',
 'targetToothSegmentId': 'trajectory.plan',
 'targetToothBoundsRoi': 'trajectory.plan',
 'trajectoryLine': 'trajectory.plan',
 'trajectoryPlacementMode': 'trajectory.plan',
 'assistedTrajectoryEntries': 'trajectory.plan',
 'assistedTrajectoryCount': 'trajectory.plan',
 'step6OpenedTargetGeometryModel': 'trajectory.plan',
 'step6OpenedTrajectoryLine': 'trajectory.plan',
 'templateSupportToothSegmentIdsJson': 'support.selection',
 'draftTemplateSupportModel': 'support.selection',
 'targetDockingReferencePlane': 'dock.assembly',
 'targetDockingAssemblyModel': 'dock.assembly',
 'targetDockingPatternRadiusMm': 'dock.assembly',
 'targetDockingOuterDiameterMm': 'dock.assembly',
 'targetDockingBoreDiameterMm': 'dock.assembly',
 'targetDockingConnectorDiameterMm': 'dock.assembly',
 'targetDockingConnectorThicknessMm': 'dock.assembly',
 'targetDockingSharedDepthMm': 'dock.assembly',
 'targetDockingYawDeg': 'dock.assembly',
 'targetDockingCollisionClearanceMm': 'dock.assembly',
 'targetDockingYawConfirmed': 'dock.assembly',
 'targetDockingMeasurementsVisible': 'dock.assembly',
 'targetDockingIndividualDepthsEnabled': 'dock.assembly',
 'targetDockingDepth1Mm': 'dock.assembly',
 'targetDockingDepth2Mm': 'dock.assembly',
 'targetDockingDepth3Mm': 'dock.assembly',
 'targetDockingDepth4Mm': 'dock.assembly',
 'templateSupportBoundaryCurve': 'support.surface',
 'templateSupportBoundaryPlane': 'support.surface',
 'templateSupportPlaneDepthMm': 'support.surface',
 'templateSupportCrownCapPercent': 'support.surface',
 'templateSupportCurveSamplingSpacingMm': 'support.surface',
 'templateTerminalSupportCoveragePercent': 'support.surface',
 'templateSupportSelectionMode': 'support.surface',
 'templateSupportDirectionReversed': 'support.surface',
 'visibleTemplateSupportModel': 'support.surface',
 'templateInsertionDirection': 'support.surface',
 'templateUndercutAngleToleranceDeg': 'template.build',
 'templateInterproximalReliefMm': 'template.build',
 'templateBlockoutSafetyMm': 'template.build',
 'templateShellVoxelClosingMm': 'template.build',
 'templateUndercutSurfaceModel': 'template.build',
 'templateUndercutBlockoutModel': 'template.build',
 'patientContactShellModel': 'template.build',
 'templateShellRoi': 'template.build',
 'templateShellClearanceMm': 'template.build',
 'templateShellThicknessMm': 'template.build',
 'templateSamplingSpacingMm': 'template.build',
 'templateChannelDiameterMm': 'template.build',
 'templateSleeveOuterDiameterMm': 'template.build',
 'templateSleeveInnerDiameterMm': 'template.build',
 'templateSleeveHeightMm': 'template.build',
 'templateDockingClearanceMm': 'template.build',
 'templateReinforcementRadialMm': 'template.build',
 'templateReinforcementDepthMm': 'template.build',
 'templateDockingAssemblyModel': 'template.build',
 'templateDockingClearanceModel': 'template.build',
 'templateDockingReinforcementModel': 'template.build',
 'templateDockingChannelsModel': 'template.build',
 'finalPrintableTemplateModel': 'template.build',
 'researchTemplateShellModel': 'template.build',
 'researchTemplateSleeveModel': 'template.build',
 'templateFinalizationMode': 'template.verify',
 'templateFinalizationKeepRegion': 'template.verify',
 'templateFinalizationViewLocked': 'template.verify',
 'templateFinalizationYawLocked': 'template.verify',
 'templateTrimPlane': 'template.verify',
 'templateTrimCurve': 'template.verify',
 'finalizedTemplateShellModel': 'template.verify',
 'step6TaskHomeJson': 'simulation.home',
 'robotJoint1TaskMinDeg': 'simulation.home',
 'robotJoint1TaskMaxDeg': 'simulation.home',
 'robotJoint2TaskMinMm': 'simulation.home',
 'robotJoint2TaskMaxMm': 'simulation.home',
 'robotJoint3TaskMinDeg': 'simulation.home',
 'robotJoint3TaskMaxDeg': 'simulation.home',
 'robotJoint4TaskMinMm': 'simulation.home',
 'robotJoint4TaskMaxMm': 'simulation.home',
 'robotJoint5TaskMinDeg': 'simulation.home',
 'robotJoint5TaskMaxDeg': 'simulation.home',
 'step6AssistedLimitProposalJson': 'simulation.workspace',
 'robotWorkspaceSampleCount': 'simulation.workspace',
 'step6MotionDiagnosticJson': 'history',
 'step6PlannerComparisonJson': 'history',
 'step6ConfirmedTaskJson': 'runtime',
 'step6CollisionSceneAuditJson': 'runtime',
 'step6PlanningContextImported': 'runtime',
 'robotJoint1Deg': 'runtime',
 'robotJoint2Mm': 'runtime',
 'robotJoint3Deg': 'runtime',
 'robotJoint4Mm': 'runtime',
 'robotJoint5Deg': 'runtime',
 'robotKeyboardNudgeEnabled': 'runtime',
 'robotTranslationStepMm': 'simulation.planning',
 'robotRotationStepDeg': 'simulation.planning',
 'step6ApproachStandoffMm': 'simulation.planning',
 'step6AllowSpindleGuideContact': 'simulation.planning',
 'step6MouthBarrierEdgeMode': 'simulation.planning',
 'step6ShowMouthBarrier': 'simulation.planning',
 'step6ShowMouthBarrierSurface': 'simulation.planning',
 'step6ShowReachEnvelope': 'simulation.planning',
 'step6MouthBarrierOpacity': 'simulation.planning',
 'step6ShowTaskSpaceBox': 'simulation.planning',
 'step6TaskSpaceBoxSideMm': 'simulation.planning',
 'step6TaskSpaceBoxOpacity': 'simulation.planning',
 'step6TerminalContactToleranceMm': 'simulation.planning',
 'step6TrajectoryCorridorRadiusMm': 'simulation.planning',
 'step6ToolFrame': 'simulation.planning',
 'robotMotionPlanSampleCount': 'simulation.planning',
 'robotCoarseSelfClearanceMm': 'simulation.planning',
 'robotEnvironmentClearanceMm': 'simulation.planning',
 'dentoCaseId': 'identity',
 'dentoCaseResumeCheckpoint': 'navigation'}

DEFAULTS = {'caseName': '',
 'workflowStageIndex': '-1',
 'useLauncherBackendConfiguration': 'True',
 'wslDistribution': '',
 'wslPythonPath': '',
 'stagingRoot': '',
 'inferenceDevice': 'cuda:0',
 'targetToothSegmentId': '',
 'trajectoryPlacementMode': 'Manual',
 'assistedTrajectoryCount': '2',
 'targetDockingPatternRadiusMm': '10.0',
 'targetDockingOuterDiameterMm': '3.0',
 'targetDockingBoreDiameterMm': '1.0',
 'targetDockingConnectorDiameterMm': '3.5',
 'targetDockingConnectorThicknessMm': '2.0',
 'targetDockingSharedDepthMm': '5.0',
 'targetDockingYawDeg': '35.0',
 'targetDockingCollisionClearanceMm': '0.5',
 'targetDockingYawConfirmed': 'False',
 'targetDockingMeasurementsVisible': 'True',
 'targetDockingIndividualDepthsEnabled': 'False',
 'targetDockingDepth1Mm': '5.0',
 'targetDockingDepth2Mm': '5.0',
 'targetDockingDepth3Mm': '5.0',
 'targetDockingDepth4Mm': '5.0',
 'templateSupportToothSegmentIdsJson': '[]',
 'templateSupportPlaneDepthMm': '4.0',
 'templateSupportCrownCapPercent': '10.0',
 'templateSupportCurveSamplingSpacingMm': '0.5',
 'templateTerminalSupportCoveragePercent': '50.0',
 'templateSupportSelectionMode': 'Smallest',
 'templateSupportDirectionReversed': 'False',
 'templateUndercutAngleToleranceDeg': '5.0',
 'templateInterproximalReliefMm': '1.0',
 'templateBlockoutSafetyMm': '0.1',
 'templateShellVoxelClosingMm': '0.3',
 'templateShellClearanceMm': '0.3',
 'templateShellThicknessMm': '1.5',
 'templateSamplingSpacingMm': '0.3',
 'templateChannelDiameterMm': '2.0',
 'templateSleeveOuterDiameterMm': '4.4',
 'templateSleeveInnerDiameterMm': '2.1',
 'templateSleeveHeightMm': '2.5',
 'templateDockingClearanceMm': '0.3',
 'templateReinforcementRadialMm': '1.0',
 'templateReinforcementDepthMm': '2.0',
 'templateFinalizationMode': 'PlaneCut',
 'templateFinalizationKeepRegion': 'Negative',
 'templateFinalizationViewLocked': 'True',
 'templateFinalizationYawLocked': 'False',
 'caseFoundationOpeningRevision': '0',
 'caseFoundationPreviewUncommitted': 'False',
 'step6CaseJawTargetGapMm': '40.0',
 'step6CaseJawPreparationMode': 'ClosedSource',
 'step6CaseJawPreparationJson': '',
 'step6CaseJawLastFailureJson': '',
 'robotJoint1Deg': '0.0',
 'robotJoint2Mm': '0.0',
 'robotJoint3Deg': '0.0',
 'robotJoint4Mm': '0.0',
 'robotJoint5Deg': '0.0',
 'robotTranslationStepMm': '1.0',
 'robotRotationStepDeg': '1.0',
 'robotKeyboardNudgeEnabled': 'False',
 'robotBaseMountLocked': 'False',
 'step6BasePlacementStatus': 'Unlocked',
 'step6BasePlacementSource': 'operator-unlocked',
 'step6BasePlacementRevision': '0',
 'step6ForeheadProxyWidthMm': '140.0',
 'step6ForeheadProxyHeightMm': '85.0',
 'step6ForeheadProxyDepthMm': '28.0',
 'step6ForeheadProxyOffsetMm': '0.0',
 'step6TaskHomeJson': '',
 'step6AssistedLimitProposalJson': '',
 'step6ConfirmedTaskJson': '',
 'step6CollisionSceneAuditJson': '',
 'step6MotionDiagnosticJson': '',
 'step6PlannerComparisonJson': '',
 'dentoCaseSchemaVersion': '1.0',
 'step6EnvironmentJson': '',
 'step6TrajectoryRegistryJson': '',
 'step6SchemaMigrationPending': 'False',
 'step6ApproachStandoffMm': '2.0',
 'step6AllowSpindleGuideContact': 'False',
 'step6MouthBarrierEdgeMode': 'gum_line',
 'step6ShowMouthBarrier': 'True',
 'step6ShowMouthBarrierSurface': 'False',
 'step6ShowReachEnvelope': 'True',
 'step6MouthBarrierOpacity': '0.12',
 'step6ShowTaskSpaceBox': 'False',
 'step6TaskSpaceBoxSideMm': '200.0',
 'step6TaskSpaceBoxOpacity': '0.1',
 'step6TerminalContactToleranceMm': '0.25',
 'step6TrajectoryCorridorRadiusMm': '0.75',
 'step6ToolFrame': 'dentobot_drill_tcp',
 'step6CbctVolumeRenderingNodeId': '',
 'step6CbctOpacity': '0.18',
 'step6MasksOpacity': '0.45',
 'step6RobotOpacity': '1.0',
 'step6GoalRobotOpacity': '0.35',
 'step6GuidesOpacity': '0.65',
 'step6MountPlaneOpacity': '0.35',
 'step6TrajectoryOpacity': '1.0',
 'step6ForeheadProxyOpacity': '0.2',
 'step6CollisionAuditOpacity': '0.45',
 'step6PlanningContextImported': 'False',
 'robotMotionPlanSampleCount': '12',
 'robotCoarseSelfClearanceMm': '5.0',
 'robotEnvironmentClearanceMm': '2.0',
 'robotWorkspaceSampleCount': '600',
 'robotJoint1TaskMinDeg': '-25.38',
 'robotJoint1TaskMaxDeg': '334.62',
 'robotJoint2TaskMinMm': '0.0',
 'robotJoint2TaskMaxMm': '80.0',
 'robotJoint3TaskMinDeg': '-62.46',
 'robotJoint3TaskMaxDeg': '297.54',
 'robotJoint4TaskMinMm': '0.0',
 'robotJoint4TaskMaxMm': '75.0',
 'robotJoint5TaskMinDeg': '-180.0',
 'robotJoint5TaskMaxDeg': '180.0',
 'sceneDisplayPresetJson': '',
 'dentoCaseId': '',
 'dentoCaseResumeCheckpoint': ''}

NODE_FIELDS = ('inputVolume',
 'inspectedVolume',
 'inspectedSegmentation',
 'roundTripVolume',
 'teethSegmentation',
 'targetToothBoundsRoi',
 'trajectoryLine',
 'assistedTrajectoryEntries',
 'targetDockingReferencePlane',
 'targetDockingAssemblyModel',
 'draftTemplateSupportModel',
 'templateSupportBoundaryCurve',
 'templateSupportBoundaryPlane',
 'visibleTemplateSupportModel',
 'templateInsertionDirection',
 'templateUndercutSurfaceModel',
 'templateUndercutBlockoutModel',
 'patientContactShellModel',
 'templateShellRoi',
 'templateDockingAssemblyModel',
 'templateDockingClearanceModel',
 'templateDockingReinforcementModel',
 'templateDockingChannelsModel',
 'finalPrintableTemplateModel',
 'researchTemplateShellModel',
 'researchTemplateSleeveModel',
 'templateTrimPlane',
 'templateTrimCurve',
 'finalizedTemplateShellModel',
 'robotBaseTransform',
 'robotMountPlane',
 'robotForeheadProxyModel',
 'step6CaseJawLandmarks',
 'step6CaseJawTransform',
 'step6CaseJawGapLine',
 'step6OpenedLowerJawModel',
 'step6FixedUpperAnatomy',
 'step6MovingLowerAnatomy',
 'step6TargetJawFallbackAnatomy',
 'step6OpenedTargetGeometryModel',
 'step6OpenedTrajectoryLine',
 'caseFoundationFixedUpperVolume',
 'caseFoundationMovingLowerVolume')

RESUME_INDICES = {'source.volume': 1,
 'anatomy.segmentation': 2,
 'foundation.pose': 3,
 'foundation.base': 3,
 'trajectory.plan': 4,
 'support.selection': 5,
 'dock.assembly': 6,
 'support.surface': 7,
 'template.build': 8,
 'template.verify': 9,
 'simulation.home': 10,
 'simulation.workspace': 10,
 'simulation.planning': 10}

# Step 5C evidence lives on a retained Step 5B model as well as in the registry.
# Omitted checkpoints must remove these attributes without changing geometry.
NODE_ATTRIBUTE_OWNERS = {
    "DENTOBOT.VerificationJson": "template.verify",
    "DENTOBOT.VerificationState": "template.verify",
    "DENTOBOT.Step5CStaleReason": "template.verify",
}
